name: CI

on: push

jobs:
  eslint-prettier-and-tsc:
    name: Lint, Prettier and TSC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - name: ESLint
        run: yarn eslint .
      - name: prettier
        run: yarn prettier -c .
      - name: TSC
        run: yarn tsc --project tsconfig.json
