name: CI

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - run: yarn eslint .
      - run: yarn prettier -c .
      - run: yarn tsc --project tsconfig.json
